/* Generated by tools/generate_mist_glyph_assets.py. */
#include "mist_glyph_assets.h"

const mist_glyph_font_glyph_t mist_glyph_font[MIST_GLYPH_FONT_COUNT] = {
    {'0', 3u, {0x07u, 0x05u, 0x05u, 0x05u, 0x07u}},
    {'1', 3u, {0x02u, 0x06u, 0x02u, 0x02u, 0x07u}},
    {'2', 3u, {0x06u, 0x01u, 0x02u, 0x04u, 0x07u}},
    {'3', 3u, {0x06u, 0x01u, 0x02u, 0x01u, 0x06u}},
    {'4', 3u, {0x05u, 0x05u, 0x07u, 0x01u, 0x01u}},
    {'5', 3u, {0x07u, 0x04u, 0x06u, 0x01u, 0x06u}},
    {'6', 3u, {0x03u, 0x04u, 0x07u, 0x05u, 0x07u}},
    {'7', 3u, {0x07u, 0x01u, 0x02u, 0x02u, 0x02u}},
    {'8', 3u, {0x07u, 0x05u, 0x07u, 0x05u, 0x07u}},
    {'9', 3u, {0x07u, 0x05u, 0x07u, 0x01u, 0x06u}},
    {'A', 3u, {0x02u, 0x05u, 0x07u, 0x05u, 0x05u}},
    {'B', 3u, {0x06u, 0x05u, 0x06u, 0x05u, 0x06u}},
    {'C', 3u, {0x03u, 0x04u, 0x04u, 0x04u, 0x03u}},
    {'D', 3u, {0x06u, 0x05u, 0x05u, 0x05u, 0x06u}},
    {'E', 3u, {0x07u, 0x04u, 0x06u, 0x04u, 0x07u}},
    {'F', 3u, {0x07u, 0x04u, 0x06u, 0x04u, 0x04u}},
    {'G', 3u, {0x03u, 0x04u, 0x05u, 0x05u, 0x03u}},
    {'H', 3u, {0x05u, 0x05u, 0x07u, 0x05u, 0x05u}},
    {'I', 3u, {0x07u, 0x02u, 0x02u, 0x02u, 0x07u}},
    {'J', 3u, {0x01u, 0x01u, 0x01u, 0x05u, 0x02u}},
    {'K', 3u, {0x05u, 0x05u, 0x06u, 0x05u, 0x05u}},
    {'L', 3u, {0x04u, 0x04u, 0x04u, 0x04u, 0x07u}},
    {'M', 5u, {0x11u, 0x1bu, 0x15u, 0x11u, 0x11u}},
    {'N', 4u, {0x09u, 0x0du, 0x0bu, 0x09u, 0x09u}},
    {'O', 3u, {0x02u, 0x05u, 0x05u, 0x05u, 0x02u}},
    {'P', 3u, {0x06u, 0x05u, 0x06u, 0x04u, 0x04u}},
    {'Q', 3u, {0x02u, 0x05u, 0x05u, 0x07u, 0x03u}},
    {'R', 3u, {0x06u, 0x05u, 0x06u, 0x05u, 0x05u}},
    {'S', 3u, {0x03u, 0x04u, 0x02u, 0x01u, 0x06u}},
    {'T', 3u, {0x07u, 0x02u, 0x02u, 0x02u, 0x02u}},
    {'U', 3u, {0x05u, 0x05u, 0x05u, 0x05u, 0x07u}},
    {'V', 3u, {0x05u, 0x05u, 0x05u, 0x05u, 0x02u}},
    {'W', 5u, {0x11u, 0x11u, 0x15u, 0x1bu, 0x11u}},
    {'X', 3u, {0x05u, 0x05u, 0x02u, 0x05u, 0x05u}},
    {'Y', 3u, {0x05u, 0x05u, 0x02u, 0x02u, 0x02u}},
    {'Z', 3u, {0x07u, 0x01u, 0x02u, 0x04u, 0x07u}},
    {':', 1u, {0x00u, 0x01u, 0x00u, 0x01u, 0x00u}},
    {'%', 3u, {0x05u, 0x01u, 0x02u, 0x04u, 0x05u}},
    {'?', 3u, {0x06u, 0x01u, 0x02u, 0x00u, 0x02u}},
    {'-', 3u, {0x00u, 0x00u, 0x07u, 0x00u, 0x00u}},
    {'/', 3u, {0x01u, 0x01u, 0x02u, 0x04u, 0x04u}},
    {' ', 2u, {0x00u, 0x00u, 0x00u, 0x00u, 0x00u}},
    {'.', 1u, {0x00u, 0x00u, 0x00u, 0x00u, 0x01u}},
    {'+', 3u, {0x00u, 0x02u, 0x07u, 0x02u, 0x00u}},
};

static const uint16_t mist_icon_0_rows[12] = {0x07ffu, 0x0202u, 0x01dcu, 0x00f8u, 0x0070u, 0x0000u, 0x0020u, 0x0000u, 0x0088u, 0x0124u, 0x0272u, 0x07ffu};
static const uint16_t mist_icon_1_rows[11] = {0x0180u, 0x1fffu, 0x0180u, 0x0000u, 0x000cu, 0x1fffu, 0x000cu, 0x0000u, 0x0600u, 0x1fffu, 0x0600u};
static const uint8_t mist_icon_1_levels[143] = {0u, 0u, 0u, 0u, 224u, 224u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 61u, 61u, 61u, 61u, 224u, 224u, 61u, 61u, 61u, 61u, 61u, 61u, 61u, 0u, 0u, 0u, 0u, 224u, 224u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 224u, 224u, 0u, 0u, 61u, 61u, 61u, 61u, 61u, 61u, 61u, 61u, 61u, 224u, 224u, 61u, 61u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 224u, 224u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 224u, 224u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 61u, 61u, 224u, 224u, 61u, 61u, 61u, 61u, 61u, 61u, 61u, 61u, 61u, 0u, 0u, 224u, 224u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u};
static const uint16_t mist_icon_2_rows[5] = {0x1123u, 0x1b54u, 0x1574u, 0x1154u, 0x1153u};
static const uint16_t mist_icon_3_rows[5] = {0x22e9u, 0x224du, 0x2a4bu, 0x3649u, 0x22e9u};
static const uint16_t mist_icon_4_rows[7] = {0x0008u, 0x0010u, 0x0020u, 0x007fu, 0x0020u, 0x0010u, 0x0008u};
static const uint16_t mist_icon_5_rows[7] = {0x0001u, 0x0002u, 0x0004u, 0x0208u, 0x0110u, 0x00a0u, 0x0040u};
static const uint8_t mist_icon_5_levels[70] = {0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 242u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 242u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 242u, 0u, 0u, 242u, 0u, 0u, 0u, 0u, 0u, 242u, 0u, 0u, 0u, 0u, 242u, 0u, 0u, 0u, 242u, 0u, 0u, 0u, 0u, 0u, 0u, 242u, 0u, 242u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 242u, 0u, 0u, 0u, 0u, 0u, 0u};
static const uint16_t mist_icon_6_rows[7] = {0x0008u, 0x002au, 0x0049u, 0x0041u, 0x0041u, 0x0022u, 0x001cu};
static const uint16_t mist_icon_7_rows[12] = {0x000cu, 0x000cu, 0x000cu, 0x000cu, 0x000cu, 0x000cu, 0x000cu, 0x0000u, 0x0021u, 0x0000u, 0x000cu, 0x000cu};
static const uint8_t mist_icon_7_levels[72] = {0u, 0u, 222u, 222u, 0u, 0u, 0u, 0u, 222u, 222u, 0u, 0u, 0u, 0u, 222u, 222u, 0u, 0u, 0u, 0u, 222u, 222u, 0u, 0u, 0u, 0u, 222u, 222u, 0u, 0u, 0u, 0u, 222u, 222u, 0u, 0u, 0u, 0u, 222u, 222u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 36u, 0u, 0u, 0u, 0u, 36u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 230u, 230u, 0u, 0u, 0u, 0u, 230u, 230u, 0u, 0u};
static const uint16_t mist_icon_8_rows[7] = {0x0010u, 0x0018u, 0x001cu, 0x001eu, 0x001cu, 0x0018u, 0x0010u};
static const uint16_t mist_icon_9_rows[7] = {0x0036u, 0x0036u, 0x0036u, 0x0036u, 0x0036u, 0x0036u, 0x0036u};
static const uint16_t mist_icon_10_rows[7] = {0x0000u, 0x003eu, 0x0022u, 0x0022u, 0x0022u, 0x003eu, 0x0000u};
static const uint16_t mist_icon_11_rows[9] = {0x0101u, 0x0082u, 0x0044u, 0x0028u, 0x0010u, 0x0028u, 0x0044u, 0x0082u, 0x0101u};
static const uint8_t mist_icon_11_levels[81] = {224u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 224u, 0u, 224u, 0u, 0u, 0u, 0u, 0u, 224u, 0u, 0u, 0u, 224u, 0u, 0u, 0u, 224u, 0u, 0u, 0u, 0u, 0u, 224u, 0u, 224u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 224u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 224u, 0u, 224u, 0u, 0u, 0u, 0u, 0u, 224u, 0u, 0u, 0u, 224u, 0u, 0u, 0u, 224u, 0u, 0u, 0u, 0u, 0u, 224u, 0u, 224u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 224u};
static const uint16_t mist_icon_12_rows[7] = {0x007fu, 0x0041u, 0x005du, 0x0041u, 0x0051u, 0x0041u, 0x007fu};
static const uint16_t mist_icon_13_rows[12] = {0x0000u, 0x03f8u, 0x07fcu, 0x07fcu, 0x0ffeu, 0x0ffeu, 0x0ffeu, 0x0ffeu, 0x07fcu, 0x07fcu, 0x03f8u, 0x0000u};
static const uint8_t mist_icon_13_levels[156] = {0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 11u, 22u, 33u, 36u, 33u, 22u, 11u, 0u, 0u, 0u, 0u, 0u, 11u, 33u, 54u, 71u, 77u, 71u, 54u, 33u, 11u, 0u, 0u, 0u, 0u, 29u, 60u, 90u, 113u, 123u, 113u, 90u, 60u, 29u, 0u, 0u, 0u, 13u, 45u, 83u, 123u, 157u, 173u, 157u, 123u, 83u, 45u, 13u, 0u, 0u, 19u, 54u, 97u, 144u, 193u, 227u, 193u, 144u, 97u, 54u, 19u, 0u, 0u, 19u, 54u, 97u, 144u, 193u, 227u, 193u, 144u, 97u, 54u, 19u, 0u, 0u, 13u, 45u, 83u, 123u, 157u, 173u, 157u, 123u, 83u, 45u, 13u, 0u, 0u, 0u, 29u, 60u, 90u, 113u, 123u, 113u, 90u, 60u, 29u, 0u, 0u, 0u, 0u, 11u, 33u, 54u, 71u, 77u, 71u, 54u, 33u, 11u, 0u, 0u, 0u, 0u, 0u, 11u, 22u, 33u, 36u, 33u, 22u, 11u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u};
static const uint16_t mist_icon_14_rows[11] = {0x0000u, 0x0404u, 0x08e2u, 0x10e1u, 0x10e1u, 0x10e1u, 0x10e1u, 0x10e1u, 0x08e2u, 0x0404u, 0x0000u};
static const uint16_t mist_icon_15_rows[8] = {0x0000u, 0x0020u, 0x0060u, 0x0060u, 0x0070u, 0x0078u, 0x007fu, 0x003eu};
static const uint8_t mist_icon_15_levels[56] = {0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 150u, 0u, 0u, 0u, 0u, 0u, 159u, 159u, 0u, 0u, 0u, 0u, 0u, 169u, 169u, 0u, 0u, 0u, 0u, 0u, 179u, 179u, 179u, 0u, 0u, 0u, 0u, 188u, 188u, 188u, 188u, 0u, 0u, 0u, 198u, 198u, 198u, 198u, 198u, 198u, 198u, 0u, 207u, 207u, 207u, 207u, 207u, 0u};
static const uint16_t mist_icon_16_rows[7] = {0x0078u, 0x0048u, 0x004au, 0x004fu, 0x004au, 0x0048u, 0x0078u};
static const uint16_t mist_icon_17_rows[5] = {0x0011u, 0x0019u, 0x0015u, 0x0013u, 0x0011u};
static const uint16_t mist_icon_18_rows[5] = {0x000eu, 0x0011u, 0x0010u, 0x0011u, 0x000eu};
static const uint16_t mist_icon_19_rows[7] = {0x071cu, 0x0802u, 0x1001u, 0x11f1u, 0x1001u, 0x0802u, 0x071cu};
static const uint8_t mist_icon_19_levels[91] = {0u, 0u, 204u, 204u, 204u, 0u, 0u, 0u, 204u, 204u, 204u, 0u, 0u, 0u, 204u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 204u, 0u, 204u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 204u, 204u, 0u, 0u, 0u, 235u, 235u, 235u, 235u, 235u, 0u, 0u, 0u, 204u, 204u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 204u, 0u, 204u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 204u, 0u, 0u, 0u, 204u, 204u, 204u, 0u, 0u, 0u, 204u, 204u, 204u, 0u, 0u};
static const uint16_t mist_icon_20_rows[13] = {0x0010u, 0x01f8u, 0x07fcu, 0x0418u, 0x0c10u, 0x0800u, 0x0800u, 0x0800u, 0x0c00u, 0x0404u, 0x071cu, 0x01f0u, 0x0000u};
static const uint8_t mist_icon_20_levels[169] = {0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 255u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 199u, 199u, 199u, 199u, 255u, 255u, 0u, 0u, 0u, 0u, 0u, 199u, 199u, 199u, 199u, 199u, 199u, 255u, 255u, 255u, 0u, 0u, 0u, 0u, 199u, 0u, 0u, 0u, 0u, 0u, 255u, 255u, 0u, 0u, 0u, 0u, 199u, 199u, 0u, 0u, 0u, 0u, 0u, 255u, 0u, 0u, 0u, 0u, 0u, 199u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 199u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 199u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 199u, 199u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 199u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 199u, 0u, 0u, 0u, 0u, 199u, 199u, 199u, 0u, 0u, 0u, 199u, 199u, 199u, 0u, 0u, 0u, 0u, 0u, 0u, 199u, 199u, 199u, 199u, 199u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u};
static const uint16_t mist_icon_21_rows[10] = {0x07ffu, 0x0401u, 0x0401u, 0x0471u, 0x0471u, 0x0401u, 0x0401u, 0x07ffu, 0x0020u, 0x0070u};
static const uint8_t mist_icon_21_levels[110] = {178u, 178u, 178u, 178u, 178u, 178u, 178u, 178u, 178u, 178u, 178u, 178u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 178u, 178u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 178u, 178u, 0u, 0u, 0u, 242u, 242u, 242u, 0u, 0u, 0u, 178u, 178u, 0u, 0u, 0u, 242u, 242u, 242u, 0u, 0u, 0u, 178u, 178u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 178u, 178u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 178u, 178u, 178u, 178u, 178u, 178u, 178u, 178u, 178u, 178u, 178u, 178u, 0u, 0u, 0u, 0u, 0u, 178u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 178u, 178u, 178u, 0u, 0u, 0u, 0u};
static const uint16_t mist_icon_22_rows[13] = {0x0000u, 0x03f8u, 0x060cu, 0x0c06u, 0x08e2u, 0x09f2u, 0x09f2u, 0x09f2u, 0x08e2u, 0x0c06u, 0x060cu, 0x03f8u, 0x0000u};
static const uint16_t mist_icon_23_rows[15] = {0x0380u, 0x0478u, 0x0404u, 0x1802u, 0x2002u, 0x2401u, 0x4201u, 0x4101u, 0x4201u, 0x447au, 0x2002u, 0x2002u, 0x100cu, 0x0e10u, 0x01e0u};
static const uint8_t mist_icon_23_levels[225] = {0u, 0u, 0u, 0u, 0u, 89u, 89u, 89u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 89u, 0u, 0u, 0u, 89u, 89u, 89u, 89u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 89u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 89u, 0u, 0u, 0u, 0u, 89u, 89u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 89u, 0u, 0u, 89u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 89u, 0u, 0u, 89u, 0u, 0u, 255u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 89u, 89u, 0u, 0u, 0u, 0u, 255u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 89u, 89u, 0u, 0u, 0u, 0u, 0u, 255u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 89u, 89u, 0u, 0u, 0u, 0u, 255u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 89u, 89u, 0u, 0u, 0u, 255u, 0u, 0u, 0u, 255u, 255u, 255u, 255u, 0u, 89u, 0u, 0u, 89u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 89u, 0u, 0u, 89u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 89u, 0u, 0u, 0u, 89u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 89u, 89u, 0u, 0u, 0u, 0u, 0u, 89u, 89u, 89u, 0u, 0u, 0u, 0u, 89u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 89u, 89u, 89u, 89u, 0u, 0u, 0u, 0u, 0u};
static const uint16_t mist_icon_24_rows[15] = {0x0840u, 0x0c4cu, 0x0458u, 0x2670u, 0x3260u, 0x1ac0u, 0x0fdeu, 0x7ff0u, 0x07feu, 0x1fc6u, 0x3360u, 0x6670u, 0x0c58u, 0x0848u, 0x0040u};
static const uint16_t mist_icon_25_rows[15] = {0x0040u, 0x00e0u, 0x01f0u, 0x0040u, 0x044eu, 0x0e4eu, 0x0444u, 0x0444u, 0x0248u, 0x0150u, 0x00e0u, 0x0040u, 0x00e0u, 0x00e0u, 0x0040u};
static const uint16_t mist_icon_26_rows[15] = {0x0010u, 0x0018u, 0x0014u, 0x0112u, 0x0094u, 0x0058u, 0x0030u, 0x0030u, 0x0058u, 0x0094u, 0x0112u, 0x0014u, 0x0018u, 0x0010u, 0x0000u};
static const uint16_t mist_icon_27_rows[9] = {0x0ffeu, 0x0802u, 0x0adau, 0x0adbu, 0x0adbu, 0x0adbu, 0x0adau, 0x0802u, 0x0ffeu};

const mist_glyph_icon_t mist_glyph_icons[MIST_GLYPH_ICON_COUNT] = {
    {"番茄钟", 11u, 12u, mist_icon_0_rows, NULL},
    {"设置", 13u, 11u, mist_icon_1_rows, mist_icon_1_levels},
    {"macOS", 13u, 5u, mist_icon_2_rows, NULL},
    {"Windows / Linux", 14u, 5u, mist_icon_3_rows, NULL},
    {"返回", 7u, 7u, mist_icon_4_rows, NULL},
    {"确认", 10u, 7u, mist_icon_5_rows, mist_icon_5_levels},
    {"电源", 7u, 7u, mist_icon_6_rows, NULL},
    {"警告", 6u, 12u, mist_icon_7_rows, mist_icon_7_levels},
    {"播放", 7u, 7u, mist_icon_8_rows, NULL},
    {"暂停", 7u, 7u, mist_icon_9_rows, NULL},
    {"取消", 7u, 7u, mist_icon_10_rows, NULL},
    {"错误", 9u, 9u, mist_icon_11_rows, mist_icon_11_levels},
    {"配置", 7u, 7u, mist_icon_12_rows, NULL},
    {"灯光", 13u, 12u, mist_icon_13_rows, mist_icon_13_levels},
    {"振动", 13u, 11u, mist_icon_14_rows, NULL},
    {"待机", 7u, 8u, mist_icon_15_rows, mist_icon_15_levels},
    {"退出", 7u, 7u, mist_icon_16_rows, NULL},
    {"普通模式", 5u, 5u, mist_icon_17_rows, NULL},
    {"Codex", 5u, 5u, mist_icon_18_rows, NULL},
    {"蓝牙连接", 13u, 7u, mist_icon_19_rows, mist_icon_19_levels},
    {"重启", 13u, 13u, mist_icon_20_rows, mist_icon_20_levels},
    {"系统", 11u, 10u, mist_icon_21_rows, mist_icon_21_levels},
    {"普通模式 · 方格核心", 13u, 13u, mist_icon_22_rows, NULL},
    {"Codex · 终端标志", 15u, 15u, mist_icon_23_rows, mist_icon_23_levels},
    {"Claude Code · 放射标志", 15u, 15u, mist_icon_24_rows, NULL},
    {"USB · 有线连接", 13u, 15u, mist_icon_25_rows, NULL},
    {"Bluetooth · 蓝牙", 9u, 15u, mist_icon_26_rows, NULL},
    {"Battery", 13u, 9u, mist_icon_27_rows, NULL},
};

const mist_glyph_point_t mist_glyph_boring_cells[MIST_GLYPH_BORING_CELL_COUNT] = {
    {-2, 10},
    {-1, 10},
    {0, 10},
    {-2, 11},
    {1, 11},
    {-2, 12},
    {-1, 12},
    {0, 12},
    {-2, 13},
    {1, 13},
    {-2, 14},
    {-1, 14},
    {0, 14},
    {4, 10},
    {5, 10},
    {3, 11},
    {6, 11},
    {3, 12},
    {6, 12},
    {3, 13},
    {6, 13},
    {4, 14},
    {5, 14},
    {8, 10},
    {9, 10},
    {10, 10},
    {8, 11},
    {11, 11},
    {8, 12},
    {9, 12},
    {10, 12},
    {8, 13},
    {10, 13},
    {8, 14},
    {11, 14},
    {13, 10},
    {14, 10},
    {15, 10},
    {14, 11},
    {14, 12},
    {14, 13},
    {13, 14},
    {14, 14},
    {15, 14},
    {17, 10},
    {20, 10},
    {17, 11},
    {18, 11},
    {20, 11},
    {17, 12},
    {19, 12},
    {20, 12},
    {17, 13},
    {20, 13},
    {17, 14},
    {20, 14},
    {23, 10},
    {24, 10},
    {25, 10},
    {22, 11},
    {22, 12},
    {24, 12},
    {25, 12},
    {22, 13},
    {25, 13},
    {23, 14},
    {24, 14},
    {25, 14},
};

const mist_glyph_font_glyph_t *mist_glyph_font_find(char character)
{
    for (size_t index = 0; index < MIST_GLYPH_FONT_COUNT; ++index) {
        if (mist_glyph_font[index].character == character) return &mist_glyph_font[index];
    }
    return NULL;
}

const mist_glyph_icon_t *mist_glyph_icon_get(uint8_t resource_id)
{
    return resource_id < MIST_GLYPH_ICON_COUNT ? &mist_glyph_icons[resource_id] : NULL;
}
